/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-11-03 16:55:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class connexion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel =\"stylesheet\" href = \"/PE2I/css/main.css\"/>\r\n");
      out.write("<link rel =\"stylesheet\" href = \"/PE2I/css/connexion.css\"/>\t\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<title>PETUT</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"conteneurGeneral\">\r\n");
      out.write("\t\t<div class=\"connexion\">\r\n");
      out.write("\t\t\t<button class=\"boutonEnseignant\" id=\"boutonEnseignant\" type=\"button\">Enseignant</button>\r\n");
      out.write("\t\t\t<button class=\"boutonEleve\" id=\"boutonEleve\" type=\"button\">Elève</button>\r\n");
      out.write("\t\t\t<form id=\"formEnseignant\" method=\"post\" action=\"connexion\">\r\n");
      out.write("\t\t    \t<fieldset>\r\n");
      out.write("\t\t        \t<legend>Connexion enseignant</legend>\r\n");
      out.write("\t\t                           \r\n");
      out.write("\t\t\t\t\t<label for=\"Identifiant\">Nom de compte<span class=\"requis\"></span></label>\r\n");
      out.write("\t\t            <input type=\"Identifiant\" id=\"connexionIdentifiant\" name=\"connexionIdentifiant\" size=\"20\" maxlength=\"60\" />\r\n");
      out.write("\t\t            <span class=\"erreur\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${traitement.erreurs['connexionIdentifiant']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t            <br />\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t            <label for=\"connexionMotdepasse\">Mot de passe <span class=\"requis\"></span></label>\r\n");
      out.write("\t\t            <input type=\"password\" id=\"connexionMotdepasse\" name=\"connexionMotdepasse\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("\t\t            <span class=\"erreur\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${traitement.erreurs['connexionMotdepasse']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t            <br />\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t            <input type=\"submit\" value=\"connexion\" class=\"sansLabel\" />\r\n");
      out.write("\t\t            <br />\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t            <!-- <p class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty form.erreurs ? 'succes' : 'erreur'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${form.resultat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>-->\r\n");
      out.write("\t\t     \t</fieldset>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form id=\"formEleve\" method=\"post\" action=\"connexion\">\r\n");
      out.write("\t\t    \t<fieldset>\r\n");
      out.write("\t\t        \t<legend>Connexion élève</legend>\r\n");
      out.write("\t\t                           \r\n");
      out.write("\t\t\t\t\t<label for=\"Identifiant\">Identifiant<span class=\"requis\"></span></label>\r\n");
      out.write("\t\t            <input type=\"Identifiant\" id=\"connexionIdentifiant\" name=\"connexionIdentifiant\" size=\"20\" maxlength=\"60\" />\r\n");
      out.write("\t\t            <span class=\"erreur\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${traitement.erreurs['connexionIdentifiant']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t            <br />\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t            <label for=\"connexionMotdepasse\">Mot de passe <span class=\"requis\"></span></label>\r\n");
      out.write("\t\t            <input type=\"password\" id=\"connexionMotdepasse\" name=\"connexionMotdepasse\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("\t\t            <span class=\"erreur\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${traitement.erreurs['connexionMotdepasse']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t            <br />\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t            <input type=\"submit\" value=\"connexion\" class=\"sansLabel\" />\r\n");
      out.write("\t\t            <br />\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t            <p class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty form.erreurs ? 'succes' : 'erreur'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${form.resultat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t     \t</fieldset>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\tdocument.getElementById('formEnseignant').style.visibility = 'hidden';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$( '#boutonEleve' ).click(function(){\r\n");
      out.write("\t\t\trunEffect('boutonEleve')});\r\n");
      out.write("\t\t$( '#boutonEnseignant' ).click(function(){\r\n");
      out.write("\t\t\trunEffect('boutonEnseignant')});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction runEffect(bouton){\r\n");
      out.write("\t\t\tif(bouton == 'boutonEleve'){\r\n");
      out.write("\t\t\t\tdocument.getElementById('formEleve').style.visibility = 'visible';\r\n");
      out.write("\t\t\t\tdocument.getElementById('formEnseignant').style.visibility = 'hidden';\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdocument.getElementById('formEleve').style.visibility = 'hidden';\r\n");
      out.write("\t\t\t\tdocument.getElementById('formEnseignant').style.visibility = 'visible';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
