/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-11-08 21:45:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.eleve;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class forum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\t<link rel =\"stylesheet\" href = \"/PE2I/css/forum.css\"/>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.6.1.min.js\"></script>\r\n");
      out.write("\t\t<title>PE2I</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div style=\"position: fixed;width:100%;z-index:10;\">\r\n");
      out.write("\t\t\t<div class=enTete>\r\n");
      out.write("\t\t\t\t<p class=\"boutonHautBas\" id=\"boutonHautBas\">Modules</p>\r\n");
      out.write("\t\t\t\t<ul class=\"nav\" id=\"nav\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"navigation\" id=\"navigation\">\r\n");
      out.write("\t\t\t\t<ul id=\"context\">\r\n");
      out.write("\t\t\t\t\t<li class=\"semestres\" id=\"semestre\">\r\n");
      out.write("\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"conteneurGeneral\" id=\"conteneurGeneral\">\r\n");
      out.write("\t\t\t<!-- <div class=\"documents\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"/PE2I/images/eleves/forum/sujet.jpg\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"/PE2I/images/eleves/forum/corriger.jpg\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"/PE2I/images/eleves/forum/documentAImporter.jpg\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>sujet</td>\r\n");
      out.write("\t\t\t\t\t\t<td>corrigé</td>\r\n");
      out.write("\t\t\t\t\t\t<td>document à importer</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar idModuleClick;\r\n");
      out.write("\t\t\t$( '.semestre' ).click(function(){\r\n");
      out.write("\t\t\t\t$(\".listeSujets\").remove();\r\n");
      out.write("\t\t\t\t$(\".listeTopics\").remove();\r\n");
      out.write("\t\t\t\t$('.forum').hide(200);\r\n");
      out.write("\t\t\t\t$(\"#navigation\").find('li').each(\r\n");
      out.write("\t\t\t\t\tfunction(){\r\n");
      out.write("\t\t\t\t\t\tif(this.id != \"semestre\"){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#\"+this.id).remove();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t)\r\n");
      out.write("\t\t\t\tidSemestre = this.getAttribute('id');\r\n");
      out.write("\t\t\t\tif(idSemestre != null){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : '/PE2I/eleves/forum',\r\n");
      out.write("\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\tdata : 'idSemestre=' + idSemestre,\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(valeur){\r\n");
      out.write("\t\t\t\t\t\t\t//listeSemestreCLick.addNumeroSemestre(idSemestre,valeur);\r\n");
      out.write("\t\t\t\t\t\t\tvar listeUes = JSON.parse(valeur);\r\n");
      out.write("\t\t\t\t\t\t\tfor(i = 0; i < listeUes.length; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar li = $(\"<li class='parent' id='parent\"+i+\"'/>\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar p = $(\"<p class='ue' id='ue\"+i+\"'> UE \"+listeUes[i].numero + \" : \" +listeUes[i].libelle+\"</p>\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar div = $(\"<div class='rubrique' id='rubrique\"+i+\"'/>\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ul = $(\"<ul id=moduleUe\"+i+\"></ul>\")\r\n");
      out.write("\t\t\t\t\t\t\t\t$(li).appendTo($(\"#context\"));\r\n");
      out.write("\t\t\t\t\t\t\t\t$(p).appendTo(li);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(div).appendTo(li);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(ul).appendTo(div);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfor(j = 0; j < listeUes.length; j++){\r\n");
      out.write("\t\t\t\t\t\t\t\tfor(k=0;k<listeUes[j].l.length;k++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar li2 = $(\"<li class='module' id='module\"+listeUes[j].l[k].id+\"'><p>\"+listeUes[j].l[k].numero+\"</p></li>\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(li2).appendTo($(\"#moduleUe\"+j));\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$(\".module\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$( '.parent' ).click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".module\").slideUp();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#\"+this.id).find('li').each( \r\n");
      out.write("\t\t\t\t\t\t\t\t\tfunction(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(($(this)).is(\":visible\")){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcacher($(this).attr('id'));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tafficher($(this).attr('id'));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tfunction afficher(id){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#\"+id).slideDown();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction cacher(id){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#\"+id).slideUp();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$(\".module\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".listeSujets\").remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".listeTopics\").remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t$('.forum').show(200);\r\n");
      out.write("\t\t\t\t\t\t\t\tidModuleClick = (this.id).replace('module', '');\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdataType : 'text'\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//function ajax pour afficher les sujets d'une matière donnée et d'un forum donnée\r\n");
      out.write("\t\t\t$( '.forum' ).click(function(){\r\n");
      out.write("\t\t\t\tif(!haut)\r\n");
      out.write("\t\t\t\t\tslideBarreModule();\r\n");
      out.write("\t\t\t\tif(idModuleClick != null){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : '/PE2I/eleves/forum',\r\n");
      out.write("\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\tdata : 'idModule=' + idModuleClick + '&idForum='+((this.id).replace('forum','')),\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(valeur){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".listeSujets\").remove();\r\n");
      out.write("\t\t\t\t\t\t\t$(\".listeTopics\").remove();\r\n");
      out.write("\t\t\t\t\t\t\tvar listeSujets = JSON.parse(valeur);\r\n");
      out.write("\t\t\t\t\t\t\t//identifiant = identifiant du sujet se trouvant dans la listeSujets.id\r\n");
      out.write("\t\t\t\t\t\t\tvar div = $('<div class=\"listeSujets\">');\r\n");
      out.write("\t\t\t\t\t\t\tvar table = $(\"<table id='tableauSujets' class='tableau'>\");\r\n");
      out.write("\t\t\t\t\t\t\tvar tbody = $('<tbody class=\"body\">');\r\n");
      out.write("\t\t\t\t\t\t\tvar entete = $('<tr class=\"enteteTableau\"> <th>N°</th> <th>Nom</th></tr>');\r\n");
      out.write("\t\t\t\t\t\t\t$(div).appendTo($('.conteneurGeneral'));\r\n");
      out.write("\t\t\t\t\t\t\t$(table).appendTo(div);\r\n");
      out.write("\t\t\t\t\t\t\t$(tbody).appendTo(table);\r\n");
      out.write("\t\t\t\t\t\t\t$(entete).appendTo(tbody);\r\n");
      out.write("\t\t\t\t\t\t\tfor(i = 0; i < listeSujets.length; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar tr = $(\"<tr class='champTableau' id='sujet\"+listeSujets[i].id+\"'></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar tdNumero = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar tdNom = $('<td></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\ttdNumero.text(listeSujets[i].numero);\r\n");
      out.write("\t\t\t\t\t\t\t\ttdNom.text(listeSujets[i].nom);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(tr).appendTo(tbody);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(tdNumero).appendTo(tr);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(tdNom).appendTo(tr);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$('.champTableau').click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\tidSujet = ((this.id).replace('sujet',''));\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : '/PE2I/eleves/forum',\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata : 'idSujet=' + idSujet,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(valeur){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\".listeSujets\").remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\".listeTopics\").remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar listeObjet = JSON.parse(valeur);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar div = $('<div class=\"documents\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar table = $(\"<table>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar tbody = $('<tbody>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar tr1 = $(\"<tr></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar tr2 = $(\"<tr></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(div).appendTo($('.conteneurGeneral'));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(table).appendTo(div);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(tbody).appendTo(table);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(tr1).appendTo(tbody);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(tr2).appendTo(tbody);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(listeObjet[0].sujet != null){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar td1 = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar td2 = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar img = $(\"<img src='/PE2I/images/eleves/forum/\"+listeObjet[0].sujet.nom+\".jpg'/>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(td1).appendTo(tr1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(td2).appendTo(tr2);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(img).appendTo(td1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(listeObjet[0].correction != null){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar td1 = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar td2 = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar img = $(\"<img src='/PE2I/images/eleves/forum/\"+listeObjet[0].correction.nom+\".jpg'/>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(td1).appendTo(tr1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(td2).appendTo(tr2);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(img).appendTo(td1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(listeObjet[0].listeDocumentsAImporter[0] != null){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar td1 = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar td2 = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar img = $(\"<img src='/PE2I/images/eleves/forum/\"+listeObjet[0].listeDocumentsAImporter[0].nom+\".jpg'/>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(td1).appendTo(tr1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(td2).appendTo(tr2);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(img).appendTo(td1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//identifiant = identifiant du sujet se trouvant dans la listeSujets.id\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar div = $('<div class=\"listeTopics\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar table = $(\"<table id='tableauTopic' class='tableau'>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar tbody = $('<tbody class=\"body\">');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar entete = $('<tr class=\"enteteTableau\"> <th>statut</th> <th>question</th> <th>auteur</th> <th>date</th> <th>reponse</th> </tr>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(div).appendTo($('.conteneurGeneral'));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(table).appendTo(div);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(tbody).appendTo(table);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(entete).appendTo(tbody);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor(i = 0; i < listeObjet[1].length; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tr = $(\"<tr class='champTableau' id='sujet\"+listeObjet[1][i].id+\"'></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tdStatut = $(\"<td></td>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tdQuestion = $('<td></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tdAuteur = $('<td></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tdDate = $('<td></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar tdReponse = $('<td></td>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttdStatut.text(listeObjet[1][i].statut);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttdQuestion.text(listeObjet[1][i].question);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttdAuteur.text(listeObjet[1][i].auteur);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttdDate.text(listeObjet[1][i].date);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttdReponse.text(listeObjet[1][i].nbReponse);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(tr).appendTo(tbody);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(tdStatut).appendTo(tr);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(tdQuestion).appendTo(tr);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(tdAuteur).appendTo(tr);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(tdDate).appendTo(tr);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(tdReponse).appendTo(tr);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdataType : 'text'\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t    },\r\n");
      out.write("\t\t\t\t\t\tdataType : 'text'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar haut = false;\r\n");
      out.write("\t\t\tfunction slideBarreModule(){\r\n");
      out.write("\t\t\t\tif(!haut){\r\n");
      out.write("\t\t\t\t\t$('#context').slideUp()\r\n");
      out.write("\t\t\t\t\tif($('#context').is(':animated')){\r\n");
      out.write("\t\t\t\t\t\tcheckAnimate();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\thaut = true;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('conteneurGeneral').style.marginLeft=\"20%\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('conteneurGeneral').style.marginRight=\"20%\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('conteneurGeneral').style.width=\"60%\";\r\n");
      out.write("\t\t\t\t\t$('#context').slideDown();\r\n");
      out.write("\t\t\t\t\tif($('#context').is(':animated')){\r\n");
      out.write("\t\t\t\t\t\tcheckAnimate();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\thaut = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\tfunction checkAnimate() {\r\n");
      out.write("\t            if( $( '#context' ).is( ':animated' )) {\r\n");
      out.write("\t                setTimeout(function() {\r\n");
      out.write("\t                    checkAnimate();\r\n");
      out.write("\t                }, 0 );\r\n");
      out.write("\t            }else{\r\n");
      out.write("\t            \tif(haut){\r\n");
      out.write("\t            \t\tdocument.getElementById('conteneurGeneral').style.marginLeft=\"0%\";\r\n");
      out.write("\t            \t\tdocument.getElementById('conteneurGeneral').style.marginRight=\"0%\";\r\n");
      out.write("\t            \t\tdocument.getElementById('conteneurGeneral').style.width=\"100%\";\r\n");
      out.write("\t            \t}\t\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t\t$( '#boutonHautBas' ).click(function(){\r\n");
      out.write("\t\t\t\tslideBarreModule()});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$('.forum').hide();\r\n");
      out.write("\t\t\t//var longueurDivTableau = ($(\".tableau\").width()*100);\r\n");
      out.write("\t\t\t//var pourcentage = (longueurDivTableau/($(document).width()));\r\n");
      out.write("\t\t\t//var resultat = ((100-pourcentage)/2)-20;\r\n");
      out.write("\t\t\t//alert(resultat);\t\r\n");
      out.write("\t\t\t//var string = resultat+'%';\r\n");
      out.write("\t\t\t//document.getElementById('tableauSujets').style.marginLeft = string;\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/eleve/forum.jsp(17,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("forum");
      // /WEB-INF/jsp/eleve/forum.jsp(17,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/eleve/forum.jsp(17,5) '${listeForum}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listeForum}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<li class=\" partie\"><a class=\"forum\" id=\"forum");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${forum.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</a></li>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/eleve/forum.jsp(18,65) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${forum.nom}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/jsp/eleve/forum.jsp(26,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("semestre");
      // /WEB-INF/jsp/eleve/forum.jsp(26,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/eleve/forum.jsp(26,7) '${listeSemestre}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listeSemestre}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<input class= \"semestre\" id = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${semestre.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" type=\"radio\" name=\"semestre\">");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/jsp/eleve/forum.jsp(27,84) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("S${semestre.numero}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    }
    return false;
  }
}
